const CSV_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vRfaC8Z9GDnjyLsdMCw6Lr4bBx5jvgmDHJy-fBNao-HIvDSFPaiFJU4gPDgmo9pfXgYYJmVXJjVP-Gs/pub?gid=1006372394&single=true&output=csv';
const ROSTER=[
['Maxi Yamal','Jugador'],['Lester Mbappé','Jugador'],['Vale Modrić','Jugador'],['Jose Bellingham','Jugador'],['Lucho Vinícius','Jugador'],['Chalo Haaland','Jugador'],['Jairen Courtois','Arquero'],['Juanjo Insigne','Jugador'],['Luxito Dibu','Arquero'],['Ale Neymar','Jugador'],['Walala Ramos','Defensa'],['Rafael Raphinha','Jugador']
];
let rows=[],stats=[];
const V=document.querySelector('#view'), sync=document.querySelector('#sync'), buttons=[...document.querySelectorAll('nav button')];
const yes=v=>['si','sí','yes','1','true','x'].includes(String(v||'').trim().toLowerCase());
const num=v=>{let n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0};
function parseCSV(t){let out=[],row=[],v='',q=false;for(let i=0;i<t.length;i++){let c=t[i],n=t[i+1];if(c=='"'&&q&&n=='"'){v+='"';i++}else if(c=='"')q=!q;else if(c==','&&!q){row.push(v);v=''}else if((c=='\n'||c=='\r')&&!q){if(c=='\r'&&n=='\n')i++;row.push(v);if(row.some(x=>x.trim()))out.push(row);row=[];v=''}else v+=c}row.push(v);if(row.some(x=>x.trim()))out.push(row);return out}
function normalize(table){let hi=table.findIndex(r=>r.some(c=>c.trim().toLowerCase()==='fecha'));if(hi<0)throw Error('No encontré encabezados');let h=table[hi].map(x=>x.trim());return table.slice(hi+1).filter(r=>r.some(x=>x.trim())).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]||''])))}
function calc(){stats=ROSTER.map(([name,pos])=>{let rr=rows.filter(r=>r.Jugador?.trim()===name && yes(r['Jugó']));let s={name,pos,pj:rr.length,g:0,a:0,w:0,mvp:0,y:0,r:0,ga:0,gc:0,cs:0,pts:0};rr.forEach(x=>{s.g+=num(x.Goles);s.a+=num(x.Asistencias);s.w+=yes(x.Victoria)?1:0;s.mvp+=yes(x.MVP)?1:0;s.y+=num(x.Amarillas);s.r+=num(x.Rojas);s.gc+=num(x['Goles recibidos']);s.cs+=yes(x['Valla invicta'])?1:0});s.ga=s.g+s.a;s.pts=s.g*3+s.a*2+s.w*2+s.mvp*3;return s}).sort((a,b)=>b.pts-a.pts||b.ga-a.ga)}
const top=k=>[...stats].sort((a,b)=>b[k]-a[k])[0];
function empty(){return `<div class="card empty"><b>⚽ Temporada lista para comenzar</b><span class="tag">Todavía no hay fechas cargadas en Google Sheets.</span><p>Cuando ingreses la primera jornada, Maitenliga se actualizará automáticamente.</p></div>`}
function inicio(){let played=rows.filter(r=>yes(r['Jugó']));if(!played.length)return `<div class="hero"><h1>♛ MAITENLIGA 2026</h1><div class="tag">La liga de los amigos</div></div>${empty()}`;let dates=[...new Set(played.map(r=>r.Fecha))],last=dates[dates.length-1],lr=played.filter(r=>r.Fecha===last),m=lr.find(r=>yes(r.MVP));return `<div class="hero"><h1>♛ MAITENLIGA 2026</h1><div class="tag">La liga de los amigos</div></div><h2>ÚLTIMA FECHA</h2><div class="card"><div class="tag">Fecha ${last}</div><h2>${lr.length} jugadores participaron</h2></div>${m?`<div class="card"><div class="yellow">⭐ MVP DE LA FECHA</div><h2>${m.Jugador}</h2><div class="stats"><div><b>${num(m.Goles)}</b><small>Goles</small></div><div><b>${num(m.Asistencias)}</b><small>Asist.</small></div><div><b>⭐</b><small>MVP</small></div><div><b>${yes(m.Victoria)?'🏆':'—'}</b><small>Victoria</small></div><div><b>${num(m.Amarillas)}</b><small>🟨</small></div></div></div>`:''}`}
function ranking(){if(!rows.some(r=>yes(r['Jugó'])))return empty();let tr=stats.map((p,i)=>`<tr><td>${['🥇','🥈','🥉'][i]||i+1}</td><td>${p.name}</td><td>${p.pj}</td><td>${p.g}</td><td>${p.a}</td><td>${p.mvp}</td><td><b>${p.pts}</b></td></tr>`).join('');return `<h2>🏆 RANKING</h2><div class="card"><table><tr><th>#</th><th>Jugador</th><th>PJ</th><th>G</th><th>A</th><th>MVP</th><th>PTS</th></tr>${tr}</table></div><h2>LÍDERES</h2><div class="grid"><div class="card award">⚽ Goleador<b>${top('g').name}</b><span class="yellow">${top('g').g} goles</span></div><div class="card award">🎯 Asistidor<b>${top('a').name}</b><span class="yellow">${top('a').a} asist.</span></div><div class="card award">⭐ Más MVP<b>${top('mvp').name}</b><span class="yellow">${top('mvp').mvp} MVP</span></div><div class="card award">🟨 Tarjetas<b>${top('y').name}</b><span class="yellow">${top('y').y} amarillas</span></div></div>`}
function jugadores(){return `<h2>👥 JUGADORES</h2>${stats.map((p,i)=>`<button class="card player" onclick="profile('${p.name.replaceAll("'","\\'")}')"><span><b>${p.name}</b><span class="tag" style="display:block">${p.pos}</span></span><span class="pill">${p.pts} pts ›</span></button>`).join('')}`}
window.profile=name=>{let p=stats.find(x=>x.name===name);V.innerHTML=`<button onclick="go('jugadores')" style="background:none;border:0;color:var(--y);font-weight:bold">← Jugadores</button><div class="card"><h1>${p.name}</h1><div class="tag">${p.pos}</div></div><div class="card"><div class="stats"><div><b>${p.pj}</b><small>PJ</small></div><div><b>${p.g}</b><small>Goles</small></div><div><b>${p.a}</b><small>Asist.</small></div><div><b>${p.mvp}</b><small>MVP</small></div><div><b>${p.pts}</b><small>Pts</small></div></div>${p.pos==='Arquero'?`<hr style="border-color:var(--line)"><div class="stats"><div><b>${p.gc}</b><small>Recibidos</small></div><div><b>${p.cs}</b><small>Vallas inv.</small></div></div>`:''}</div>`}
function historial(){if(!rows.some(r=>yes(r['Jugó'])))return empty();return `<h2>📊 DATOS QUE NADIE PIDIÓ</h2><div class="card"><div class="fact">🔥 <b>${top('g').name}</b> manda en goles con ${top('g').g}.</div><div class="fact">🎯 <b>${top('a').name}</b> lidera las asistencias con ${top('a').a}.</div><div class="fact">🏆 <b>${top('w').name}</b> suma ${top('w').w} victorias.</div><div class="fact">🪓 <b>${top('y').name}</b> lidera las amarillas con ${top('y').y}.</div></div>`}
window.go=p=>{buttons.forEach(b=>b.classList.toggle('active',b.dataset.page===p));V.innerHTML=({inicio,ranking,jugadores,historial}[p]||inicio)();scrollTo(0,0)};buttons.forEach(b=>b.onclick=()=>go(b.dataset.page));
async function load(){try{let res=await fetch(CSV_URL+'&_='+Date.now(),{cache:'no-store'});if(!res.ok)throw Error('HTTP '+res.status);rows=normalize(parseCSV(await res.text()));calc();sync.textContent='● Google Sheets conectado · '+new Date().toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'});go('inicio')}catch(e){calc();sync.textContent='⚠ No pude leer Google Sheets';V.innerHTML=`<div class="card empty"><b>No pude conectar con la planilla</b><p>Revisa que FECHAS siga publicada como CSV y vuelve a cargar la página.</p></div>`;console.error(e)}}load();
